run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    rules:
      - name: exported
        disabled: true
      - name: context-as-argument
        disabled: false
  nolintlint:
    require-specific: true
  errorlint:
    errorf: false
  gci:
    sections:
      - standard
      - default
      - localmodule
linters:
  enable-all: true

  disable:
    # deprecated linters
    - exportloopref

    # conflicting/cover same issues
    - forcetypeassert # covered by errcheck

    # personal preference
    - gocritic
    - depguard
    - funlen
    - exhaustruct
    - gochecknoglobals
    - err113
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
    # premature optimisation that creates inconsistent code (sometimes Sprintf, sometimes string concatenation)
    # consider enabling _if_ you've profile performance _and_ Sprintf calls are slowing you down
    - perfsprint
